name: Feature tests
on: push
jobs:
  unit-test:
      name: unit tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install modules
          run: yarn
        - name: run unit tests
          run: yarn test